### ISSUE TITLE
Privacy Policy - With Scanner

### ISSUE THREAD

**Issue by Osama-qa** [lntechadmin/USDA#22]
The following is a list of opportunities to improve the accessibility of USDAplant. Each item corresponds to an outlined area on the attached screenshot.

Item label
[0,0][1080,2196]
This item may not have a label readable by screen readers.

![Privacy Policy.png](https://images.zenhubusercontent.com/62b95e0c497fa5496754651f/eac5a7e9-76e7-4deb-8aca-b984ef18c98c)

**Comment by mozfet12** [comment]
I've addressed this with a semantics widget. Please note that Flutter item labels aren't currently not supported with Accessibility Scanner. Please see [https://github.com/flutter/flutter/issues/39531](https://github.com/lntechadmin/USDA/issues/url)
