### ISSUE TITLE
About Us - With Scanner

### ISSUE THREAD

**Issue by Osama-qa** [lntechadmin/USDA#26]
The following is a list of opportunities to improve the accessibility of USDAplant. Each item corresponds to an outlined area on the attached screenshot.

Item label
[0,0][1080,2196]
This item may not have a label readable by screen readers.

![About Us.png](https://images.zenhubusercontent.com/62b95e0c497fa5496754651f/a497f1c8-29a7-4be0-8bb0-7514f02061f4)

**Comment by mozfet12** [comment]
I've addressed this with a semantics widget. Please note that Flutter item labels aren't currently not supported with Accessibility Scanner. Please see [https://github.com/flutter/flutter/issues/39531](url)
